### ISSUE TITLE
Straight up does not work

### ISSUE THREAD

**Issue by EthanThatOneKid** [elcobvg/svelte-bulma-forms#13]
```sh
[!] (svelte plugin) ParseError: Directive value must be a JavaScript expression enclosed in curly braces
node_modules\svelte-bulma-forms\src\fields\AutoCompleteField.html
22:         {rounded}
23:         {readonly}
24:         on:change="changeValue(event)"
                       ^
25:         on:focus="set({ hasFocus: true })"
26:         on:blur="set({ hasFocus: false })"
ParseError: Directive value must be a JavaScript expression enclosed in curly braces
    at error$1 (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:13483:20)
    at Parser$2.error (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:13559:10)
    at read_attribute (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:12783:25)
    at tag (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:12606:26)
    at new Parser$2 (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:13518:22)
    at parse$2 (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:13649:21)
    at compile (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\svelte\compiler.js:23734:12)
    at preprocessPromise.then.code (C:\Users\acer\Documents\GitHub\ticket-caller\node_modules\rollup-plugin-svelte\index.js:236:22)
```

**Comment by elcobvg** [comment]
What version of Svelte are you using?

**Comment by cryzer12** [comment]
please!! update to 3 version svelte

**Comment by zhenyaMaretski** [comment]
Hi. I have the same error in 3 version.

**Comment by tenebrousedge** [comment]
This code is still broken.
